# Generated by Django 3.1.3 on 2020-11-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_titulo', models.CharField(max_length=200)),
                ('curso_contenido', models.TextField()),
                ('curso_publicado', models.DateTimeField(verbose_name='fecha de publicacion')),
            ],
        ),
    ]
