# Generated by Django 3.1.3 on 2020-11-29 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 22, 44, 2, 163949), verbose_name='fecha de publicacion'),
        ),
    ]
